In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [2]:
covid_data_test= pd.read_csv(r"C:\Users\MSI\Downloads\covid19-global-forecasting-week-5\test.csv")
covid_data_train= pd.read_csv(r"C:\Users\MSI\Downloads\covid19-global-forecasting-week-5\train.csv")
covid_data_submission= pd.read_csv(r"C:\Users\MSI\Downloads\covid19-global-forecasting-week-5\submission.csv")
covid_data_train

C:\Users\MSI\AppData\Local\Temp\ipykernel_15532\909441917.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  covid_data_train= pd.read_csv(r"C:\Users\MSI\Downloads\covid19-global-forecasting-week-5\train.csv")

,Id,County,Province_State,Country_Region,Population,Weight,Date,Target,TargetValue
0,1,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-23,ConfirmedCases,0
1,2,NaN,NaN,Afghanistan,27657145,0.583587,2020-01-23,Fatalities,0
2,3,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-24,ConfirmedCases,0
3,4,NaN,NaN,Afghanistan,27657145,0.583587,2020-01-24,Fatalities,0
4,5,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-25,ConfirmedCases,0
...,...,...,...,...,...,...,...,...,...
969635,969636,NaN,NaN,Zimbabwe,14240168,0.607106,2020-06-08,Fatalities,0
969636,969637,NaN,NaN,Zimbabwe,14240168,0.060711,2020-06-09,ConfirmedCases,27
969637,969638,NaN,NaN,Zimbabwe,14240168,0.607106,2020-06-09,Fatalities,0
969638,969639,NaN,NaN,Zimbabwe,14240168,0.060711,2020-06-10,ConfirmedCases,6
969639,969640,NaN,NaN,Zimbabwe,14240168,0.607106,2020-06-10,Fatalities,0

In [3]:
print(covid_data_train.columns)

Index(['Id', 'County', 'Province_State', 'Country_Region', 'Population',
       'Weight', 'Date', 'Target', 'TargetValue'],
      dtype='object')

In [4]:
print(covid_data_train.head())

   Id County Province_State Country_Region  Population    Weight        Date  \
0   1    NaN            NaN    Afghanistan    27657145  0.058359  2020-01-23
1   2    NaN            NaN    Afghanistan    27657145  0.583587  2020-01-23
2   3    NaN            NaN    Afghanistan    27657145  0.058359  2020-01-24
3   4    NaN            NaN    Afghanistan    27657145  0.583587  2020-01-24
4   5    NaN            NaN    Afghanistan    27657145  0.058359  2020-01-25

           Target  TargetValue
0  ConfirmedCases            0
1      Fatalities            0
2  ConfirmedCases            0
3      Fatalities            0
4  ConfirmedCases            0

In [5]:
column_name = 'ConfirmedCases'

if column_name in covid_data_train.columns:
    # If the column exists, proceed with your analysis
    country_with_highest_cases = covid_data_train.groupby('Country_Region')[column_name].max().idxmax()
    print(f'A. Country/region with the highest confirmed cases: {country_with_highest_cases}')
else:
    # If the column does not exist, handle the error
    print(f"'{column_name}' column not found in the dataset.")

'ConfirmedCases' column not found in the dataset.

In [6]:
covid_data_train.head()

,Id,County,Province_State,Country_Region,Population,Weight,Date,Target,TargetValue
0,1,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-23,ConfirmedCases,0
1,2,NaN,NaN,Afghanistan,27657145,0.583587,2020-01-23,Fatalities,0
2,3,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-24,ConfirmedCases,0
3,4,NaN,NaN,Afghanistan,27657145,0.583587,2020-01-24,Fatalities,0
4,5,NaN,NaN,Afghanistan,27657145,0.058359,2020-01-25,ConfirmedCases,0

In [7]:
covid_data_train.shape

(969640, 9)

In [8]:
covid_data_train.isnull().sum()

Id                    0
County            89600
Province_State    52360
Country_Region        0
Population            0
Weight                0
Date                  0
Target                0
TargetValue           0
dtype: int64

In [9]:
covid_data_test.head()

,ForecastId,County,Province_State,Country_Region,Population,Weight,Date,Target
0,1,NaN,NaN,Afghanistan,27657145,0.058359,2020-04-27,ConfirmedCases
1,2,NaN,NaN,Afghanistan,27657145,0.583587,2020-04-27,Fatalities
2,3,NaN,NaN,Afghanistan,27657145,0.058359,2020-04-28,ConfirmedCases
3,4,NaN,NaN,Afghanistan,27657145,0.583587,2020-04-28,Fatalities
4,5,NaN,NaN,Afghanistan,27657145,0.058359,2020-04-29,ConfirmedCases

In [10]:
covid_data_train[covid_data_train['Country_Region']=='India']

,Id,County,Province_State,Country_Region,Population,Weight,Date,Target,TargetValue
40320,40321,NaN,NaN,India,1295210000,0.04766,2020-01-23,ConfirmedCases,0
40321,40322,NaN,NaN,India,1295210000,0.47660,2020-01-23,Fatalities,0
40322,40323,NaN,NaN,India,1295210000,0.04766,2020-01-24,ConfirmedCases,0
40323,40324,NaN,NaN,India,1295210000,0.47660,2020-01-24,Fatalities,0
40324,40325,NaN,NaN,India,1295210000,0.04766,2020-01-25,ConfirmedCases,0
...,...,...,...,...,...,...,...,...,...
40595,40596,NaN,NaN,India,1295210000,0.47660,2020-06-08,Fatalities,266
40596,40597,NaN,NaN,India,1295210000,0.04766,2020-06-09,ConfirmedCases,10218
40597,40598,NaN,NaN,India,1295210000,0.47660,2020-06-09,Fatalities,277
40598,40599,NaN,NaN,India,1295210000,0.04766,2020-06-10,ConfirmedCases,437
40599,40600,NaN,NaN,India,1295210000,0.47660,2020-06-10,Fatalities,-5

In [11]:
covid_data_train[covid_data_train['Country_Region']=='China']

,Id,County,Province_State,Country_Region,Population,Weight,Date,Target,TargetValue
15680,15681,NaN,Anhui,China,62550000,0.055706,2020-01-23,ConfirmedCases,8
15681,15682,NaN,Anhui,China,62550000,0.557057,2020-01-23,Fatalities,0
15682,15683,NaN,Anhui,China,62550000,0.055706,2020-01-24,ConfirmedCases,6
15683,15684,NaN,Anhui,China,62550000,0.557057,2020-01-24,Fatalities,0
15684,15685,NaN,Anhui,China,62550000,0.055706,2020-01-25,ConfirmedCases,24
...,...,...,...,...,...,...,...,...,...
25195,25196,NaN,NaN,China,1395773400,0.474908,2020-06-08,Fatalities,0
25196,25197,NaN,NaN,China,1395773400,0.047491,2020-06-09,ConfirmedCases,3
25197,25198,NaN,NaN,China,1395773400,0.474908,2020-06-09,Fatalities,0
25198,25199,NaN,NaN,China,1395773400,0.047491,2020-06-10,ConfirmedCases,11
25199,25200,NaN,NaN,China,1395773400,0.474908,2020-06-10,Fatalities,0

In [12]:
covid_data_train[covid_data_train['Country_Region']=='India']['County'].value_counts()

Series([], Name: County, dtype: int64)

In [13]:
covid_data_test.isnull().sum()

ForecastId            0
County            28800
Province_State    16830
Country_Region        0
Population            0
Weight                0
Date                  0
Target                0
dtype: int64